"""empty message

Revision ID: 4ba566d4d166
Revises: 599d800d30cf
Create Date: 2021-11-03 13:52:45.826565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba566d4d166'
down_revision = '599d800d30cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('quota', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_activity_for_date', 'activity', ['ong_id', 'date'])
    op.drop_column('activity', 'cupos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('cupos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_activity_for_date', 'activity', type_='unique')
    op.drop_column('activity', 'quota')
    # ### end Alembic commands ###
