"""empty message

Revision ID: b391d1aea1a2
Revises: e7f86cae02ce
Create Date: 2021-11-03 15:40:09.051338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b391d1aea1a2'
down_revision = 'e7f86cae02ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_voluntary_for_activity', 'voluntary', ['name', 'lastName', 'phone', 'activity_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_voluntary_for_activity', 'voluntary', type_='unique')
    # ### end Alembic commands ###
