"""empty message

Revision ID: e5b0082e8dba
Revises: b391d1aea1a2
Create Date: 2021-11-08 16:15:55.056236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b0082e8dba'
down_revision = 'b391d1aea1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ong', sa.Column('bank', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ong', 'bank')
    # ### end Alembic commands ###
