"""empty message

Revision ID: e7f86cae02ce
Revises: ce2a26ed226e
Create Date: 2021-11-03 15:04:07.883481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f86cae02ce'
down_revision = 'ce2a26ed226e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ong', ['rif'])
    op.create_unique_constraint(None, 'ong', ['logo'])
    op.create_unique_constraint(None, 'ong', ['website_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ong', type_='unique')
    op.drop_constraint(None, 'ong', type_='unique')
    op.drop_constraint(None, 'ong', type_='unique')
    # ### end Alembic commands ###
